local context = require("claude-plan.context")

describe("context", function()
  describe("get", function()
    it("returns a table with file, line, and selection keys", function()
      local result = context.get()
      assert.is_table(result)
      assert.is_not_nil(result.file)
      assert.is_not_nil(result.line)
    end)

    it("returns current file path", function()
      local result = context.get()
      assert.is_string(result.file)
    end)

    it("returns current line number", function()
      local result = context.get()
      assert.is_number(result.line)
      assert.is_true(result.line >= 1)
    end)

    it("returns nil selection in normal mode", function()
      local result = context.get()
      assert.is_nil(result.selection)
    end)

    it("returns nil start_line and end_line in normal mode", function()
      local result = context.get()
      assert.is_nil(result.start_line)
      assert.is_nil(result.end_line)
    end)
  end)
end)
