local window = require("scrawl.window")

describe("window", function()
  after_each(function()
    window.stop()
  end)

  describe("status", function()
    it("returns nil when no process has been started", function()
      assert.is_nil(window.status())
    end)
  end)

  describe("get_chan", function()
    it("returns nil when no process is running", function()
      assert.is_nil(window.get_chan())
    end)
  end)

  describe("get_buf", function()
    it("returns nil when no buffer exists", function()
      assert.is_nil(window.get_buf())
    end)
  end)

  describe("stop", function()
    it("does not error when nothing is running", function()
      assert.has_no.errors(function()
        window.stop()
      end)
    end)

    it("resets all state", function()
      window.stop()
      assert.is_nil(window.get_chan())
      assert.is_nil(window.get_buf())
      assert.is_nil(window.status())
    end)
  end)

  describe("toggle", function()
    it("creates a buffer and window on first call", function()
      window.toggle()
      assert.is_not_nil(window.get_buf())
      assert.is_true(vim.api.nvim_buf_is_valid(window.get_buf()))
    end)

    it("hides window on second call", function()
      window.toggle()
      local buf = window.get_buf()
      window.toggle()
      -- buffer should still be valid (process alive), but window hidden
      assert.is_true(vim.api.nvim_buf_is_valid(buf))
    end)

    it("reopens window on third call with same buffer", function()
      window.toggle()
      local buf = window.get_buf()
      window.toggle()
      window.toggle()
      assert.are.equal(buf, window.get_buf())
    end)
  end)
end)
